config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :fan_comments
  resources :reviews
  resources :authors
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fan_comment.rb
class FanComment < ApplicationRecord
end

app/controllers/fan_comments_controller.rb
class FanCommentsController < ApplicationController
  before_action :set_fan_comment, only: [:show, :edit, :update, :destroy]

  # GET /fan_comments
  # GET /fan_comments.json
  def index
    @fan_comments = FanComment.all
  end

  # GET /fan_comments/1
  # GET /fan_comments/1.json
  def show
  end

  # GET /fan_comments/new
  def new
    @fan_comment = FanComment.new
  end

  # GET /fan_comments/1/edit
  def edit
  end

  # POST /fan_comments
  # POST /fan_comments.json
  def create
    @fan_comment = FanComment.new(fan_comment_params)

    respond_to do |format|
      if @fan_comment.save
        format.html { redirect_to @fan_comment, notice: 'Fan comment was successfully created.' }
        format.json { render :show, status: :created, location: @fan_comment }
      else
        format.html { render :new }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fan_comments/1
  # PATCH/PUT /fan_comments/1.json
  def update
    respond_to do |format|
      if @fan_comment.update(fan_comment_params)
        format.html { redirect_to @fan_comment, notice: 'Fan comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan_comment }
      else
        format.html { render :edit }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fan_comments/1
  # DELETE /fan_comments/1.json
  def destroy
    @fan_comment.destroy
    respond_to do |format|
      format.html { redirect_to fan_comments_url, notice: 'Fan comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan_comment
      @fan_comment = FanComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fan_comment_params
      params.require(:fan_comment).permit(:author_no, :name, :body, :deleted)
    end
end

app/helpers/fan_comments_helper.rb
module FanCommentsHelper
end

app/views/fan_comments/_form.html.erb
<%= form_with(model: fan_comment, local: true) do |form| %>
  <% if fan_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fan_comment.errors.count, "error") %> prohibited this fan_comment from being saved:</h2>

      <ul>
      <% fan_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author_no %>
    <%= form.number_field :author_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :deleted %>
    <%= form.check_box :deleted %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fan_comments/edit.html.erb
<h1>Editing Fan Comment</h1>

<%= render 'form', fan_comment: @fan_comment %>

<%= link_to 'Show', @fan_comment %> |
<%= link_to 'Back', fan_comments_path %>

app/views/fan_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fan Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author no</th>
      <th>Name</th>
      <th>Body</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fan_comments.each do |fan_comment| %>
      <tr>
        <td><%= fan_comment.author_no %></td>
        <td><%= fan_comment.name %></td>
        <td><%= fan_comment.body %></td>
        <td><%= fan_comment.deleted %></td>
        <td><%= link_to 'Show', fan_comment %></td>
        <td><%= link_to 'Edit', edit_fan_comment_path(fan_comment) %></td>
        <td><%= link_to 'Destroy', fan_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fan Comment', new_fan_comment_path %>

app/views/fan_comments/new.html.erb
<h1>New Fan Comment</h1>

<%= render 'form', fan_comment: @fan_comment %>

<%= link_to 'Back', fan_comments_path %>

app/views/fan_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author no:</strong>
  <%= @fan_comment.author_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @fan_comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @fan_comment.body %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @fan_comment.deleted %>
</p>

<%= link_to 'Edit', edit_fan_comment_path(@fan_comment) %> |
<%= link_to 'Back', fan_comments_path %>